# Generated by Django 3.0.7 on 2020-06-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('emailaddress', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
